version: '3.8'

services:
  web:
    image: php:latest
    container_name: php_web
    working_dir: /var/www/html/public
    ports:
      - "80:80"
    command: ["php", "-S", "0.0.0.0:80"]
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: group_table_edits
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
